# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "timezone_local"
  s.version = "0.1.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chetan Sarva"]
  s.date = "2012-05-30"
  s.description = ""
  s.email = "chetan@evidon.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/timezone_local.rb",
    "lib/unix.rb",
    "timezone_local.gemspec"
  ]
  s.homepage = "http://github.com/chetan/timezone_local"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Determine the local system's time zone"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<tzinfo>, [">= 0.3.24"])
    else
      s.add_dependency(%q<tzinfo>, [">= 0.3.24"])
    end
  else
    s.add_dependency(%q<tzinfo>, [">= 0.3.24"])
  end
end

